image: docker.io/worldofgeese/buddhabot-devcontainer:latest
tasks:
  - command: |
      direnv allow
      glab config set check_update false
      glab auth login --token $GITLAB_TOKEN
vscode:
  extensions:
    - jetpack-io.devbox
    - ms-python.python
    - GitLab.gitlab-workflow
    - ms-python.mypy-type-checker
    - charliermarsh.ruff
    - almenon.arepl
    - njpwerner.autodocstring
    - ms-python.black-formatter
    - sourcegraph.cody-ai
