apiVersion: garden.io/v1
kind: Project
name: lbob
defaultEnvironment: prod

variables:
  ci-env-name: ${project.name}-${local.env.CI_PIPELINE_IID || 0}
  dev-env-name: ${project.name}-${local.username}
  terraform-init-root: "./terraform"

environments:
  - name: ci
    defaultNamespace: ${var.ci-env-name}
    variables:
      hostname: ${var.ci-env-name}.ci.geese.party
  - name: dev
    defaultNamespace: ${var.dev-env-name}
    variables:
      hostname: ${var.dev-env-name}.dev.geese.party
  - name: prod
    defaultNamespace: ${project.name}
    variables:
      hostname: app.geese.party

providers:
  - name: pulumi
  - name: kubernetes
    context: scw-kapsule-ams-2-devrel-1
    kubeconfig: ${var.terraform-init-root}/${providers.terraform.outputs.kubeconfig_path}
    namespace:
      name: ${environment.namespace}
      labels:
        app: kubed

    buildMode: cluster-buildkit
    clusterBuildkit:
      rootless: true
    deploymentRegistry:
      hostname: rg.nl-ams.scw.cloud
      namespace: namespace-magical-austin
    imagePullSecrets:
      - name: registry-secret
        namespace: default
    setupIngressController: null

  - name: terraform
    initRoot: ${var.terraform-init-root}
    allowDestroy: true
    autoApply: true
    variables:
      cluster_name: "scw-kapsule-ams-2-devrel-1"
      endpoint: "c50d7b47-1d34-40b5-b7c8-1709a6839609.api.k8s.nl-ams.scw.cloud:6443"
