[tool.poetry]
name = "little-bits-of-buddha"
version = "0.1.0"
description = "A Telegram bot that regularly delivers Buddhist aphorisms to its users"
authors = ["worldofgeese <59834693+worldofgeese@users.noreply.github.com>"]
license = "AGPLv3"
include = ["data.json"]

[tool.poetry.dependencies]
python = "^3.9"
Flask = "^2.0.2"
hy = {version = "1.0a4", allow-prereleases = true, python = ">=3.9,<3.11"}
hyrule = "^0.1"

[tool.poetry.dev-dependencies]
pytest-hylang = "^0.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

# For Nix to know which scripts to install in the bin/ output directory, we also need to add a scripts section:
[tool.poetry.scripts]
lbob = 'little_bits_of_buddha.shim:main'
