[tool.pdm.build]
includes = ["data.json"]
[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"

[project]
name = "little_bits_of_buddha_worldofgeese"
version = "0.1.0"
description = "A Telegram bot that regularly delivers Buddhist aphorisms to its users"
authors = [
    {name = "Tao Hansen", email = "5-worldofgeese@users.noreply.gitlab.hansen.agency"},
]
dependencies = [
    "pytest>=7.2.1",
    "uvicorn>=0.20.0",
    "fastapi>=0.91.0",
    "python-telegram-bot>=20.1",
    "dapr==1.9.0rc2",
    "dapr-ext-grpc==1.9.0rc2",
]
requires-python = ">=3.9,<4.0"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)",
    "Operating System :: OS Independent",
]


[project.urls]
"Homepage" = "https://gitlab.hansen.agency/worldofgeese/little_bits_of_buddha"
"Bug Tracker" = "https://gitlab.hansen.agency/worldofgeese/little_bits_of_buddha/-/issues"

