[tool.pdm]
[tool.pdm.dev-dependencies]
dev = [
    "isort>=5.11.4",
    "pyflakes>=3.0.1",
    "black>=22.12.0",
    "debugpy>=1.6.6",
    "ipython>=8.8.0",
    "pyright>=1.1.291",
]

[tool.pdm.build]
includes = ["data.json"]
[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"

[project]
name = "little_bits_of_buddha_worldofgeese"
version = "0.1.0"
description = "A Telegram bot that regularly delivers Buddhist aphorisms to its users"
authors = [
    {name = "Tao Hansen", email = "5-worldofgeese@users.noreply.gitlab.hansen.agency"},
]
dependencies = [
    "flask>=2.2.2",
    "pytest>=7.2.1",
]
requires-python = ">=3.9,<4.0"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)",
    "Operating System :: OS Independent",
]


[project.urls]
"Homepage" = "https://gitlab.hansen.agency/worldofgeese/little_bits_of_buddha"
"Bug Tracker" = "https://gitlab.hansen.agency/worldofgeese/little_bits_of_buddha/-/issues"

[project.scripts]

[project.optional-dependencies]

