name: Local Test

on:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: -self-hosted
    steps:
      - name: Test
        run: |
          cd "${PROJECT_DIR:-.}"
          sh scripts/run-tests.sh
        shell: bash

  lint:
    name: Lint
    runs-on: -self-hosted
    steps:
      - name: Lint
        run: |
          cd "${PROJECT_DIR:-.}"
          sh scripts/run-lint.sh
        shell: bash

  build:
    name: Build Container
    runs-on: -self-hosted
    needs: [test, lint]
    steps:
      - name: Build
        run: |
          cd "${PROJECT_DIR:-.}"
          podman build -t little-bits-of-buddha:local -f Dockerfile .
        shell: bash
