apiVersion: v1
kind: Config
preferences:
  colors: true
current-context: ${cluster_name}
contexts:
  - context:
      cluster: ${cluster_name}
      namespace: default
      user: ${cluster_name}
    name: ${cluster_name}
clusters:
  - cluster:
      server: https://${endpoint}
      insecure-skip-tls-verify: true
    name: ${cluster_name}
users:
  - name: ${cluster_name}
    user:
      token: ${token}
